### ISSUE TITLE
Asm Compilation

### ISSUE THREAD

**Issue by mppts** [m4k331/corewar#2]
Асм не компилируется из-за ошибки в библиотеке при компиляции:

ft_atoli.c: In function ‘ft_atoli’:
ft_atoli.c:17:2: error: unknown type name ‘uint64_t’; did you mean ‘u_int64_t’?
  uint64_t  res;
  ^~~~~~~~
  u_int64_t
ft_atoli.c:33:7: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
   res > 0x8000000000000000 && ft_isdigit(*str))) && sign == -1)
       ^
ft_atoli.c:36:7: error: comparison is always false due to limited range of data type [-Werror=type-limits]
   res >= 0x7FFFFFFFFFFFFFFF && ft_isdigit(*str)))
       ^~
cc1: all warnings being treated as errors

**Comment by EgorShvetsov** [comment]
Исправил на u_int64_t. На Mac OS  изменения не произошло, как компилировалась либа, так и продолжает компилироваться.  На убунте исправил ошибку компиляции, возникшую из-за наличия неиспользуемой переменной в libft/ft_memmove.c. Компилируется успешно.
